import pytest
from common_python_tasks.env import (
    inject_auto_build_args_from_env,
    load_container_env_tokens,
    parse_container_env_tokens,
)


def test_inject_auto_build_args_from_env_adds_value(monkeypatch):
    monkeypatch.setenv("WORKDIR_PATH", "/app")

    result = inject_auto_build_args_from_env({})

    assert result["WORKDIR_PATH"] == "/app"


def test_inject_auto_build_args_from_env_preserves_explicit_value(monkeypatch):
    monkeypatch.setenv("WORKDIR_PATH", "/app")

    result = inject_auto_build_args_from_env({"WORKDIR_PATH": "/custom"})

    assert result["WORKDIR_PATH"] == "/custom"


def test_parse_container_env_tokens_accepts_list_values():
    result = parse_container_env_tokens(["A=one", "B=two"])

    assert result == ["A=one", "B=two"]


def test_load_container_env_tokens_accepts_list_container_envfile(tmp_path):
    envfile = tmp_path / "container.env"
    envfile.write_text("A=one", encoding="utf-8")

    result = load_container_env_tokens(container_envfile=[str(envfile)])

    assert result == ["A=one"]


def test_load_container_env_tokens_supports_colon_delimited_envfile_string(tmp_path):
    first_envfile = tmp_path / "first.env"
    second_envfile = tmp_path / "second.env"
    first_envfile.write_text("A=one", encoding="utf-8")
    second_envfile.write_text("B=two", encoding="utf-8")

    result = load_container_env_tokens(
        container_envfile=f"{first_envfile}:{second_envfile}"
    )

    assert result == ["A=one", "B=two"]


def test_read_dotenv_parses_simple_key_value_pairs(tmp_path):
    from common_python_tasks.compose import read_dotenv

    dotenv = tmp_path / ".env"
    dotenv.write_text("KEY1=value1\nKEY2=value2\n", encoding="utf-8")

    result = read_dotenv(dotenv)

    assert result == {"KEY1": "value1", "KEY2": "value2"}


def test_read_dotenv_skips_comments_and_empty_lines(tmp_path):
    from common_python_tasks.compose import read_dotenv

    dotenv = tmp_path / ".env"
    dotenv.write_text(
        "# Comment\nKEY1=value1\n\n# Another comment\nKEY2=value2\n",
        encoding="utf-8",
    )

    result = read_dotenv(dotenv)

    assert result == {"KEY1": "value1", "KEY2": "value2"}


def test_read_dotenv_returns_empty_dict_when_file_missing(tmp_path):
    from common_python_tasks.compose import read_dotenv

    result = read_dotenv(tmp_path / "nonexistent.env")

    assert result == {}


def test_read_dotenv_strips_quotes(tmp_path):
    from common_python_tasks.compose import read_dotenv

    dotenv = tmp_path / ".env"
    dotenv.write_text("KEY1=\"quoted\"\nKEY2='single'\n", encoding="utf-8")

    result = read_dotenv(dotenv)

    assert result == {"KEY1": "quoted", "KEY2": "single"}


def test_append_dotenv_creates_header_comment(tmp_path, monkeypatch):
    from common_python_tasks.compose import append_dotenv

    monkeypatch.chdir(tmp_path)
    dotenv = tmp_path / ".env"
    dotenv.write_text("EXISTING=value\n", encoding="utf-8")

    append_dotenv(dotenv, {"NEW_KEY": "new_value"})

    content = dotenv.read_text(encoding="utf-8")
    assert "EXISTING=value" in content
    assert "NEW_KEY=new_value" in content
    assert "Auto-generated by common_python_tasks" in content


def test_get_or_generate_secret_returns_existing_env_var(monkeypatch):
    from common_python_tasks.compose import get_or_generate_secret

    monkeypatch.setenv("TEST_SECRET", "existing-value")
    result = get_or_generate_secret("TEST_SECRET")

    assert result == "existing-value"


def test_get_or_generate_secret_generates_and_stores_new_secret(tmp_path, monkeypatch):
    from common_python_tasks.compose import get_or_generate_secret

    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv("NEW_SECRET", raising=False)

    result = get_or_generate_secret("NEW_SECRET", length_bytes=16)

    assert result is not None
    assert len(result) == 32  # hex encoded 16 bytes = 32 chars
    dotenv = tmp_path / ".env"
    assert f"NEW_SECRET={result}" in dotenv.read_text(encoding="utf-8")


def test_load_container_env_file_reads_existing_file(tmp_path):
    from common_python_tasks.env import load_container_env_file

    env_file = tmp_path / ".containerenv"
    env_file.write_text("KEY=value\n", encoding="utf-8")

    result = load_container_env_file(str(env_file))

    assert result == "KEY=value"


def test_load_container_env_file_returns_none_when_missing(tmp_path):
    from unittest.mock import patch

    from common_python_tasks.env import load_container_env_file

    with patch("common_python_tasks.utils.fatal", side_effect=SystemExit(1)):
        with pytest.raises(SystemExit):
            load_container_env_file(str(tmp_path / "missing.env"))


def test_load_container_env_file_returns_none_for_empty_file(tmp_path):
    from common_python_tasks.env import load_container_env_file

    env_file = tmp_path / ".containerenv"
    env_file.write_text("\n\n", encoding="utf-8")

    result = load_container_env_file(str(env_file))

    assert result is None
